"""Sports and Tenants Model Creation along with sports config and tenant sports mapping

Revision ID: cdccbcdb8295
Revises: 0a7462ea2ca5
Create Date: 2025-11-25 15:54:17.111449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdccbcdb8295'
down_revision: Union[str, None] = '0a7462ea2ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('sport_code', sa.String(length=10), nullable=False),
        sa.Column('sport_name', sa.String(length=25), nullable=False),
        sa.Column('category', postgresql.ENUM('RACKET_SPORTS', 'FIELD_SPORTS', 'MIXED_SPORTS', 'OTHER', name='sport_category'), nullable=True),
        sa.Column('icon_url', sa.Text(), nullable=True),
        sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='sport_status'), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_sports_id'), 'sports', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_sports_sport_code'), 'sports', ['sport_code'], unique=True, schema='public')
    op.create_table('tenants',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('tenant_code', sa.String(length=10), nullable=False),
        sa.Column('logo', sa.Text(), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('tenant_uuid', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=50), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING', 'ON_HOLD', name='tenant_status'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_uuid'),
        schema='public'
    )
    op.create_index(op.f('ix_public_tenants_id'), 'tenants', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tenants_tenant_code'), 'tenants', ['tenant_code'], unique=True, schema='public')
    op.create_table('sports_config',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('sport_id', sa.Integer(), nullable=False),
        sa.Column('config_type', postgresql.ENUM(name='config_type'), nullable=False),
        sa.Column('config_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='config_status'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['sport_id'], ['public.sports.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_sports_config_id'), 'sports_config', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_sports_config_sport_id'), 'sports_config', ['sport_id'], unique=False, schema='public')
    op.create_table('tenant_sports_mapping',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('sport_id', sa.Integer(), nullable=False),
        sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='mapping_status'), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('desciption', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['sport_id'], ['public.sports.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_tenant_sports_mapping_id'), 'tenant_sports_mapping', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tenant_sports_mapping_sport_id'), 'tenant_sports_mapping', ['sport_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tenant_sports_mapping_tenant_id'), 'tenant_sports_mapping', ['tenant_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_tenant_sports_mapping_tenant_id'), table_name='tenant_sports_mapping', schema='public')
    op.drop_index(op.f('ix_public_tenant_sports_mapping_sport_id'), table_name='tenant_sports_mapping', schema='public')
    op.drop_index(op.f('ix_public_tenant_sports_mapping_id'), table_name='tenant_sports_mapping', schema='public')
    op.drop_table('tenant_sports_mapping', schema='public')
    op.drop_index(op.f('ix_public_sports_config_sport_id'), table_name='sports_config', schema='public')
    op.drop_index(op.f('ix_public_sports_config_id'), table_name='sports_config', schema='public')
    op.drop_table('sports_config', schema='public')
    op.drop_index(op.f('ix_public_tenants_tenant_code'), table_name='tenants', schema='public')
    op.drop_index(op.f('ix_public_tenants_id'), table_name='tenants', schema='public')
    op.drop_table('tenants', schema='public')
    op.drop_index(op.f('ix_public_sports_sport_code'), table_name='sports', schema='public')
    op.drop_index(op.f('ix_public_sports_id'), table_name='sports', schema='public')
    op.drop_table('sports', schema='public')
    # ### end Alembic commands ###
