"""Update Type of config_type to string instead of Enum

Revision ID: fcc9e430a22b
Revises: cdccbcdb8295
Create Date: 2025-11-26 15:44:15.161243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcc9e430a22b'
down_revision: Union[str, None] = 'cdccbcdb8295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sports_config', 'config_type',
               existing_type=postgresql.ENUM(name='config_type'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('sports_config_sport_id_fkey', 'sports_config', type_='foreignkey')
    op.create_foreign_key(None, 'sports_config', 'sports', ['sport_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('tenant_sports_mapping_sport_id_fkey', 'tenant_sports_mapping', type_='foreignkey')
    op.drop_constraint('tenant_sports_mapping_tenant_id_fkey', 'tenant_sports_mapping', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_sports_mapping', 'sports', ['sport_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'tenant_sports_mapping', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_sports_mapping', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'tenant_sports_mapping', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_sports_mapping_tenant_id_fkey', 'tenant_sports_mapping', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tenant_sports_mapping_sport_id_fkey', 'tenant_sports_mapping', 'sports', ['sport_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'sports_config', schema='public', type_='foreignkey')
    op.create_foreign_key('sports_config_sport_id_fkey', 'sports_config', 'sports', ['sport_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sports_config', 'config_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM(name='config_type'),
               existing_nullable=False)
    # ### end Alembic commands ###
